language: java
before_install: wget -P target/travis https://raw.githubusercontent.com/goodow/maven/master/settings.xml
  
before_script:
  - echo machine goodow.com login $GERRIT_USERNAME password $GERRIT_PASSWORD >> ~/.netrc
  - git clone https://goodow.com/code/drive/drive-android
script:
  - mvn clean deploy -pl :drive-parent --settings target/travis/settings.xml

env:
  global:
    - secure: Irer4ccuRBExDi+6aJlDq/lcpTAAm4fXoclcsjEXQ5lXziIrIGXsYtoE3b2DzoJyfwqW80PEQoeBHq/2XhOmyvd7RiSyMdS886WM8jjYXKZiZ3dsx3mCYZp3BEy//TmoQ7cTi3C9Q1j6bojegYKPdCevhk5BHknUucmJfug0VUs=
    - secure: fRnYfHIIQlPtjxdNlKpLdcsv4FnGCjW68oyNoZVaN4qZqs2OO8rxo/QQ7P2PAu4Qn61y2urM37tl4+lwHNcZM0XVrZDfxQqL84k9IH191G7NBI5+7ZvqU7GLDxqmDcGnybiPcR8uBjG3hPc+BppdttD7A+2rcyYidtCOvFT/2RE=
    - secure: TrqKTgj9DPaydp0Wo2JP7YQvR/c9+a3XPr6f3CRyAYuJIArKTi1KHvDCB/v2is6pOePNOC0gi8ALyoeZVgmX7QwhBfmYGvr8sax8QXjJqRwg3hBR8eeIYpJFstVLXnENWpq4rKdwXhU/aNEp3rlvBZKrBgLTC99D5EuL1qVfCQ0=
    - secure: BU/sj6jor3RdRjs5tSVOVZvVk+pLvZ1bZp4iNabwQAkW4gSr8u+pyjo4nOxF+sa0AgA4eKIE9pYNAoXDD01oATi4LslF7OxLwnJuGRnVSEH8uO9JqZXJ/RFagVq1RM5bwLzo/eCGnEic0g6hSsHDXQe6E8mvR4nZovTQ/Do8jP4=
